# Generated by Django 4.1.4 on 2023-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvpipline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
