# Generated by Django 2.2.12 on 2023-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivetabledetails',
            name='file_id',
            field=models.IntegerField(default=None),
        ),
    ]
