# Generated by Django 2.2.12 on 2023-02-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_auto_20230228_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piplinedetails',
            name='database_name',
        ),
        migrations.AddField(
            model_name='hivetabledetails',
            name='array_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='hivetabledetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
