# Generated by Django 2.2.12 on 2023-02-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_auto_20230228_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hivetabledetails',
            name='array_id',
            field=models.IntegerField(default=None),
        ),
    ]
